version: 2
jobs:
# lint is the initial job which lints the codebase using standard golangci-lint linter
  lint:
    docker:
      - image: golang:1.13.1
    steps:
      - checkout
      - run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.19.0
      - run: golangci-lint run
# test runs the ocibuilder unit tests and stores test results in TEMP_RESULTS
  test:
    environment:
      - TEST_RESULTS: /tmp/test-results
    docker:
      - image: golang:1.13.1
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Install dependencies
          command: |
            apk update && apk add curl git build-base bash
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
      - run:
          name: Run unit tests
          command: make test
# build_linux runs the build of the linux ocictl artifact and persists the binary to the circleci workspace
  build_linux:
    docker:
      - image: golang:1.13.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk update && apk add curl git build-base bash
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
      - run:
          name: Build Linux Artifact
          command: "make ocictl-linux"
      - persist_to_workspace:
          root: .
          paths:
            - dist/
# build_mac runs the build of the mac ocictl artifact and persists the binary to the circleci workspace
  build_mac:
    docker:
      - image: golang:1.13.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk update && apk add curl git build-base bash
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
      - run:
          name: Build Mac Artifact
          command: "make ocictl-mac"
      - persist_to_workspace:
          root: .
          paths:
            - dist/
# push_container pushes the ocictl container to the ocibuilder docker registry when a new tag is added to ocibuilder
  push_container:
    docker:
      - image: golang:1.13.1
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Docker Client
          command: |
            set -x
            DOCKER_VERSION="17.03.0-ce"
            curl -L -o /tmp/docker-$DOCKER_VERSION.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$DOCKER_VERSION.tgz
            tar -xz -C /tmp -f /tmp/docker-$DOCKER_VERSION.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Run Docker Build
          command: |
            make ocictl-linux
            VERSION=$(dist/ocictl --version)
            docker build -t ocibuilder/ocictl:${VERSION} -f Dockerfile .
      - run:
          name: Run Docker Push
          command: |
            VERSION=$(dist/ocictl --version)
# push_bin pushes both the linux and mac binaries to a github release when a new tag is added to ocibuilder
  push_bin:
    environment:
      - CIRCLE_PROJECT_USERNAME: ocibuilder
      - CIRCLE_PROJECT_REPONAME: ocibuilder
    docker:
      - image: golang:1.13.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish Release Binaries to GitHub
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(dist/ocictl --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./dist/

#TODO: add contexts to share env variables between different jobs
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - build_linux:
          requires:
            - test
      - build_mac:
          requires:
            - test
      - push_bin:
          requires:
            - build_linux
            - build_mac
          filters:
            branches:
              ignore: /.*/
            tags:
              # only recognise tags with semantic versioning e.g. 0.1.0
              only: /^\d+\.\d+\.\d+$/
      - push_container:
          requires:
            - build_linux
          filters:
            branches:
              ignore: /.*/
            tags:
              # only recognise tags with semantic versioning e.g. 0.1.0
              only: /^\d+\.\d+\.\d+$/